apiVersion: v1
kind: Service
metadata:
  name: f5-demo
  namespace: f5-test
spec:
  ports:
  - name: f5-hello-world-service-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: f5-hello-web-deployment
