apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
 name: f5-demo-vs
 namespace: f5-test
 labels:
   f5cr: "true"
spec:
 host: hello-demo-test.f5-test.k8s.customer.com
 ipamLabel: "iEng-testing"
 virtualServerName: "hello-demo-test"
 pools:
 - path: /
   service: f5-demo
   servicePort: 8080
   monitor:
    type: http
    send: “GET /rn”
    recv: ""
    interval: 10
    timeout: 30

