# Sample configuration for f5-ipam-controller with default provider. For persistent IP addresses upon restarts,
# volume mounts are used. securityContext is used to change mount permissions to controller user.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: f5-ipam-controller
  name: f5-ipam-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-ipam-controller
  template:
    metadata:
      labels:
        app: f5-ipam-controller
    spec:
      containers:
        - args:
            - --orchestration
            - kubernetes
            - --ip-range
            - '{"Core-uat":"10.112.179.128-10.112.179.159","Map-uat":"10.112.179.160-10.112.179.191","Generic-uat":"10.112.179.192-10.112.179.223","iEng-testing":"10.112.179.224-10.112.179.254"}'
            - --log-level
            - DEBUG
          command:
            - /app/bin/f5-ipam-controller
          image: f5networks/f5-ipam-controller:0.1.5
          imagePullPolicy: IfNotPresent
          name: f5-ipam-controller
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /app/ipamdb
              name: samplevol
      securityContext:
        fsGroup: 1200
        runAsGroup: 1200
        runAsUser: 1200
      serviceAccount: k8s-bigip-ctlr
      serviceAccountName: k8s-bigip-ctlr
      volumes:
        - name: samplevol
          persistentVolumeClaim:
            claimName: pvc-local
